Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/focal64"

    config.vm.define "vm1" do |vm1|
      vm1.vm.hostname = "vm1"
      vm1.vm.network "public_network", ip: "10.0.0.254", type: "static"
      vm1.vm.network "private_network", ip: "192.168.0.254", type: "static"
      vm1.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      vm1.vm.provision "shell", inline: <<-SCRIPT
        sudo apt update
        sudo apt install net-tools
        sudo sysctl -w net.ipv4.ip_forward=1
      SCRIPT
    end
  
    config.vm.define "vm2" do |vm2|
      vm2.vm.hostname = "vm2"
      vm2.vm.network "public_network", type: "static", ip: "10.0.0.10"
      vm2.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      vm2.vm.provision "shell", inline: <<-SCRIPT
        sudo apt update
        sudo apt install net-tools
        sudo ip route add default via 10.0.0.254
        sudo ip route replace 10.0.0.0/24 via 10.0.0.254
      SCRIPT
    end
  
    config.vm.define "vm3" do |vm3|
      vm3.vm.hostname = "vm3"

      vm3.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
      end
      #sudo iptables-save > /etc/iptables/rules.v4
      #sudo apt install iptables-persistent -y
      vm3.vm.network "private_network", type: "static", ip: "192.168.0.10"
      vm3.vm.provision "shell", inline: <<-SCRIPT
        sudo apt update
        sudo apt install net-tools
        sudo ip route add default via 192.168.0.254
        sudo ip route replace 192.168.0.0/24 via 192.168.0.254
      SCRIPT
    end
  end
  